<a href="https://colab.research.google.com/github/0xv98/Alpha-Project_0x0/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# introduction to deep learning
import torch
import numpy as np

np1 = np.random.rand(2, 4)
np1

array([[0.21276933, 0.61598905, 0.85835316, 0.43620799],
       [0.46725819, 0.03657192, 0.38078664, 0.55470371]])

In [4]:
# torch arange
import torch
my_torch1 = torch.arange(10)
my_torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# torch view
my_torch2 = my_torch1.view(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
# torch reshape
my_torch3 = my_torch2.reshape(5, 2)
my_torch3

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [22]:
# torch slice
my_torch4 = my_torch3.reshape(5,2)
my_torch4[:,1]

tensor([1, 3, 5, 7, 9])

In [23]:
# return column
my_torch5 = my_torch4.reshape(5,2)
my_torch5[:,:1]

tensor([[0],
        [2],
        [4],
        [6],
        [8]])

In [21]:
# tensor math operations
import torch
import numpy as np

tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.tensor([6, 7, 8, 9, 10])

# Addition
tensor_a + tensor_b

# Addition longhand
torch.add(tensor_a, tensor_b)

# Subtraction
tensor_a - tensor_b

# Sub function
torch.sub(tensor_a, tensor_b)

# Multiplacation
tensor_a * tensor_b

# Mul function
torch.mul(tensor_a, tensor_b)

# Division
tensor_b / tensor_a

# Div function
torch.div(tensor_b, tensor_a)

# Reminders Modulus
tensor_b % tensor_a

# Remiders function
torch.remainder(tensor_a, tensor_b)

# Exponents
tensor_a ** tensor_b

# Exponents function
torch.pow(tensor_a, tensor_b)

# Reassigment_
tensor_a.add_(tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [25]:
# Basic Neural Networks
import torch
import torch.nn as nn
import torch.nn.functional as fn

# Create a Model Class that inherits nn.Module
class Model(nn.Module):
    # Input layer (4 features of flowers (4 layers))
    def __init__(self, in_features=4, h1=8, h2=9, output=3):
        super().__init__()
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, output)

    def fowrard(self, x):
        x = fn.relu(self.fc1(x))
        x = fn.relu(self.fc2(x))
        x =self.out(x)

        return x

# Picking a manual seed
torch.manual_seed(41)
# create an instance
model = Model()

In [28]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
url = 'https://gist.githubusercontent.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a/raw/aaecbd14aeaa468cd749528f291aa8a30c2ea09e/iris_dataset.csv'
my_df = pd.read_csv(url)
my_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 5 columns]